# Generated by Django 2.2 on 2021-04-05 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('typer_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='target',
            name='for_session',
        ),
        migrations.AddField(
            model_name='session',
            name='target',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='in_sessions', to='typer_app.Target'),
            preserve_default=False,
        ),
    ]
