# Generated by Django 2.2 on 2021-04-27 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typer_app', '0002_auto_20210405_0311'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='time',
            field=models.DurationField(null=True),
        ),
    ]
